# file: roles/goss/main.yml

# get goss
- name: "get goss"
  get_url:
    url: "https://github.com/aelsabbahy/goss/releases/download/v0.3.5/goss-linux-amd64"
    dest: "/usr/local/bin/goss"
    mode: "0755"
  tags: "goss"